### ISSUE TITLE
Having exactly 10 tonics in your inventory allows for unlimited Potion II in the Secret Lab

### ISSUE THREAD

**Issue by nzchar** [fredley/warp-speed#2]
If you have exactly 10 of a given tonic, going to the secret lab and adding 10 of it to the boiler doesn't grey out the "10" button.  You can continue clicking it to add more and more.  Clicking "Boil" then yields as many Potion II items as you added tonics for.  Even more so, once a tonic has been produced, if you have exactly 0 of it, you can continue to add 10 to the boiler whenever you wish.
![image](https://cloud.githubusercontent.com/assets/4349345/9894907/7d39a470-5c7d-11e5-94cb-321b304ebf3d.png)

Horrifically addictive game btw, bravo! :)

**Comment by fredley** [comment]
Good spot, fixed in f94e09986180ca1db06e4005f054ef7f04f4ea35
